# Your solution goes here ...

version: "3.9"

services:
  app:
    build:
      context: ./product
      dockerfile: Dockerfile
    depends_on:
       db:
          condition: service_healthy
    networks:
      - app_net    
  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD : postgres
    volumes:
      - dbdata:/var/lib/postgressql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 6s
      retries: 5
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_net

volumes:
  dbdata:

networks:
  app_net:

# ..
