
version: "3.9"

services:
  app:
    build:
      context: ./product
      dockerfile: Dockerfile
    depends_on:
       db:
          condition: service_healthy
    networks:
      - app_net    
    deploy:
      replicas: 3
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/healthz || exit 1"]
      interval: 55s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD : postgres
    volumes:
      - dbdata:/var/lib/postgressql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_net
    restart: on-failure
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 10s
      retries: 3



volumes:
  dbdata:

networks:
  app_net:


